# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        kaggle: 2
        detection: 3
        segmentation: 2
        tracking: 4
        tracker: 4
        3d: 3
        reconstruct: 3
        reconstruction: 3

# 通知の閾値
score_threshold: 0
